# Maximum number of processes that can be sent to the kernel
ProcChanSize: 1000

# Minimum free frames for a process to be ready
MinimumFreeFrames: 8

# Settings for the scheduler
Sched:
  # Lower means faster
  TimeQuantum: 50

# Settings for the CPU
CPU:
  # Lower means faster
  ClockSpeed1: 300
  ClockSpeed2: 300

# Settings for the Memory
Memory:
  # Should be a power of 2
  PageSize: 32

  # Should be a power of 2
  TotalRam: 4096

  # Size of ARC Cache
  CacheSize: 128
